#!/usr/bin/env php
<?php

ini_set('date.timezone', 'Asia/Shanghai');

require __DIR__ . '/../vendor/autoload.php';


use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->addCommands([
    new \DevChen\Command\Spider(),
]);


try {
    $application->run();
} catch (Exception $exception) {
    echo $exception->getMessage();
}
